version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: foodOrder
      MYSQL_USER: gorm
      MYSQL_PASSWORD: gorm_password

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
